service: serverless-wolox

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'develop'}
  lambdaHashingVersion: 20201221

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!.git/**'
    - '!.serverless/**'
    - '!aws-sdk'
    - '!resources/**'

functions:
  GetClients:
    handler: functions/get_clients/app.handler
    environment:
      CLIENTS_TABLE: 'clients_table'
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
        - dynamodb:GetItem
        Resource: !GetAtt ClientsTable.Arn
    events:
      - http:
          path: clients/{id}
          method: get
          cors: true

  CreateClient:
    handler: functions/create_client/app.handler
    environment:
      CLIENTS_TABLE: 'clients_table'
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
        - dynamodb:PutItem
        Resource: !GetAtt ClientsTable.Arn
      - Effect: 'Allow'
        Action:
        - events:PutEvents
        Resource: 'arn:aws:events:us-east-1:550008309007:event-bus/default'
    events:
      - http:
          path: clients
          method: post
          cors: true
          request:
            schemas:
              application/json:
                schema: ${file(schemas/create_client.json)}
                name: ClientCreateModel
                description: 'Validation model for Creating Clients'

  SendGift:
    handler: functions/send_gift/app.handler
    environment:
      CLIENTS_TABLE: 'clients_table'
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
        - dynamodb:UpdateItem
        Resource: !GetAtt ClientsTable.Arn
      - Effect: 'Allow'
        Action:
        - sqs:ReceiveMessage
        Resource: !GetAtt ClientRoleQueue.Arn
    events:
      - sqs:
          arn: !GetAtt ClientRoleQueue.Arn   
      - stream:
          type: dynamodb
          arn:  !GetAtt ClientsTable.StreamArn

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/sqs.yml)}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-iam-roles-per-function